### ISSUE TITLE
Refine Documentation

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#1]
based on the initial pdf Severine and Alexis sent me (look in emails).

**Comment by alexis-michaud** [comment]
There's a LaTeX document in Overleaf, [here](https://www.overleaf.com/11342671dymgvjhkybwj#/42822791/). It can be edited online, or you can download the file and edit it locally.

**Comment by oadams** [comment]
Closing as this has been superseded by current documentation and #199
