### ISSUE TITLE
Add functionality to correctly load old metagraphs

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#117]
There occasionally are some problems loading old stored models. I've figured out how to resolve these issues (working on branch `SavedModel`) but need to integrate this functionality into model loading. The user should not need to specify the number of layers or hidden units as this is all stored in the metagraph.

There are related design issues here too. For example, it looks like adding variables when creating an rnn_ctc model puts them in a global graph, undermining the namespacing attempt behind using a class in the first place. This isn't a huge deal, as the user is only really going to be using one model at a time, but it seems like a way bugs can creep in so that should be changed.

**Comment by oadams** [comment]
In the context of defining new models, or decoding from existing models this could be an issue. The solution is probably to use Tensorflow variable namespacing/scoping.

(Note that In the context of decoding from saved models, this won't be an issue as in the `SavedModel` branch, the `decode()` function just reads from a stored metagraph: https://github.com/persephone-tools/persephone/blob/e616919d6035e9b687aef12fa5f6f98d85f45491/persephone/model.py#L48-L81)

**Comment by shuttle1987** [comment]
I'll have a look into using the Tesnorflow variable scoping.

**Comment by shuttle1987** [comment]
Will #197 close this issue?

**Comment by oadams** [comment]
It will.

**Comment by oadams** [comment]
Based on your other emails I assume you figured this out, but let me know if you want clarification.

**Comment by shuttle1987** [comment]
I think this issue is closed, please reopen if I closed in error
