### ISSUE TITLE
Create minimal test corpus

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone#166]
I really want to make a test of corpus construction that does a more complete end to end test run without depending on pulling in external data. I have a few such cases from PR #163  that will test for various things like exceptions thrown on directory structure missing and the like. I started trying to put together a more pure test case for corpus construction in 7a3cb14 but I hit a bit of a roadblock because the ffmpeg call will fail on the non-wav data contained in the .wav mock files.

Right now a vague plan I have in mind is to make a data set with a single phoneme and only 3 files, one file for testing, one file for training and one file for validation. The labels would be the one phoneme for each of those files. The wav files could be a recording of those single phonemes then encoded as a string that can be directly written to the wav file in the test case (something like base64 for example).

Having such a `Corpus` would make it much easier for us to increase test coverage on important code paths.

**Comment by shuttle1987** [comment]
I'm thinking that this particular data would likely be a bad way of testing the training part of the code but would be a good way to test the variety of other functionality that gets the data in the state required to run the training for a model.

**Comment by alexis-michaud** [comment]
In case you would like me to prepare a set of .wav files for a mock corpus, just send in the specs! (duration, with/without silence before & after, etc).

**Comment by shuttle1987** [comment]
@alexis-michaud thanks for the offer, much appreciated. @oadams what are your thoughts on this?

As an interim step I'm thinking of processing the na_tiny example into a format that could be used in the tests.

**Comment by oadams** [comment]
Thanks for the offer, Alexis, but I don't think it's needed.

The tiny set stored [here](https://cloudstor.aarnet.edu.au/plus/s/g2GreDNlDKUq9rz) (used in test_fast() in experiments/test_na.py) is just a couple hundred kilobytes, and so can just be stored in the repo. As you mention Janis, this is a good starting point. It also seems like a decent end point: I don't see what value there is in having a single-phoneme dataset. Specifically what is lacking in the WAV files of this corpus that is preventing it from being adapted to your purposes?

**Comment by shuttle1987** [comment]
What I think I'll do is encode the tiny set in the actual test code so there's no external download dependency on the tiny set and this will allow a completely in-code test case for Corpus.

Nothing is lacking, I just needed a smaller data set because encoding a substantial amount of wav file data would bloat the code repository which is undesirable. Generally speaking we wouldn't want any wav files and just work with mocks but because we use ffmpeg and that needs a wav input I think we should use real wav files for that test case.

**Comment by shuttle1987** [comment]
For reference I implemented a mock for wav files over in https://github.com/persephone-tools/persephone-web-API/pull/62
