### ISSUE TITLE
Default behavior for corpus and labels

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone#167]
`ReadyCorpus` would scan the directories to produce a list of labels, this list of labels was then passed on to the `Corpus` construction. 
If we remove `ReadyCorpus` and instead have the user use `Corpus` directly we need to figure out how to deal with `Corpus` requiring a labels parameter when in `ReadyCorpus` it was optional. 

1. Require a list of labels to be passed in as a parameter
2. Generate the labels like ReadyCorpus did previously when labels is not provided as a parameter, we can use `determine_labels` which has since been moved out of the `ReadyCorpus` class in #163

Both are very easy to do.

**Comment by shuttle1987** [comment]
I think that there might be value in creating a classmethod for corpus that attempts to build a corpus given a directory in the right format. This would in some sense fill the need that ReadyCorpus filled for use in workshops and similar

**Comment by oadams** [comment]
I missed something in the code review. Unless I'm missing something, it looks like Corpus isn't running determine_labels(). This is needed for #96 to be satisfied. What happens when the label set isn't specified?

**Comment by shuttle1987** [comment]
Currently if the label set is not provided the Corpus construction will error (hopefully). It looks like we make labels an optional parameter then check the labels in the directory of the experiment if the parameter is not provided. I'd have already put up a bug fix PR but Internet is down here today

**Comment by shuttle1987** [comment]
See #169 for relevant bugfix pull request.
