### ISSUE TITLE
Transcription interface

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone#168]
Right now `Model.transcribe` works on taking the files specified in the experiment directory and transcribes them.

I'd like to make some sort of an API that will process files to be transcribed without having to hit the filesystem to find the parameters. This would mostly make the web API easier.

Specifically I'd like to be able to pass in the paths for the audio to be transcribed in the batch and also an output path.

**Comment by oadams** [comment]
If you take a look at the decode() function in the same module that is not a Model method, that is the future: You specify the model and the files to be transcribed. It doesn't currently specify an output path but that can be changed or implemented in a wrapper function.

**Comment by shuttle1987** [comment]
I feel like this has been done now as of the work in PR #197 that fixed issues with the standalone `transcribe` function. (Feel free to re-open this issue if there was anything missing in that PR with regards to closing this issue)

**Comment by oadams** [comment]
Agreed!
