### ISSUE TITLE
Drop ipython install requirement?

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone#192]
Why do we have ipython as an install requirement for Persephone in setup.py?

https://github.com/persephone-tools/persephone/blob/11c68545e358125d6d523aa5ae39ee65f10a04c7/setup.py#L20-L21

**Comment by shuttle1987** [comment]
This is the sort of thing I would package in say a Docker image because there's definitely some utility in having it there for the tutorial. I just am aware of trying to make a minimal amount of requirements for the main library.

**Comment by oadams** [comment]
Agreed. Having it as a dependency in the docker image only and not the main tool makes sense. It would add one more step in the "native" install tutorial though.
