### ISSUE TITLE
OpenFST dependency

### ISSUE THREAD

**Issue by shuttle1987** [persephone-tools/persephone#206]
In the config (https://github.com/persephone-tools/persephone/blob/master/persephone/config.py) we have the following line that refers to the OpenFST path:

```python
# Used for lattice output
OPENFST_BIN_PATH = config_file.get("PATHS", "OPEN_FST_BIN_PATH", fallback="/home/oadams/tools/openfst-1.6.2/src/bin")
```

But as far as I can tell from a search through the code I'm not finding any use of this. Do we still need to have this dependency?

I'm searching through the dependencies right now to improve build automation and I'd rather not build anything in that's not used

**Comment by shuttle1987** [comment]
I can see that OpenFST may be required by Kaldi but is that the only way in which this is needed?

**Comment by oadams** [comment]
OpenFST is not needed so that line can be deleted. It's a relic from when I was using OpenFST to generate lattices from the CTC probabilities.
