### ISSUE TITLE
Link for Na example data is broken

### ISSUE THREAD

**Issue by kevwang1** [persephone-tools/persephone#226]
Just letting you know, the link in the documentation for the Na example data (https://cloudstor.aarnet.edu.au/plus/s/YJXTLHkYvpG85kX/download) is broken. It says "Unspecified share exception" for me.

**Comment by alexis-michaud** [comment]
Aha, well spotted! Same at my end:
![image](https://user-images.githubusercontent.com/6072524/75115362-ed376800-565d-11ea-8c49-460f7bdfb2bc.png)

@oadams A semi-permanent or permanent hosting for the preprocessed data set would be cool. What about Zenodo? It allows a 'data dump' (no requirements of detailed metadata etc) and provides a DOI.

@gw17 used a GitHub repo to host preprocessed data, [here](https://github.com/gw17/sltu_corpora).

**Comment by oadams** [comment]
@kevwang1 Thanks for raising this. I've fixed the link.
