### ISSUE TITLE
Add a bare-bones GUI (UI task #1)

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#53]
In its first version, two widgets:

1. A simple text field where the user inputs the path to the data directory (the one with `feat/` and `label/` subdirectories) OR a file explorer where you choose a data directory.
2. A run button.

Assumes the data is preprocessed and creates a ReadyCorpus object and fires up a default model.

~~tkinter.ttk could be used.~~ Make a simple web interface, which may be good if someone is using a server with GPUs.

**EDIT: Requirements**

Satisfying this issue involves making a web extension to section _2. Training a toy Na model_ in [the tutorial](https://github.com/oadams/persephone/blob/master/README.rst). That is, we assume for now that (a) the data is already on the server and (b) the data is the preprocessed Na data from the tutorial, so the `ReadyCorpus` constructor can be used. Both of these assumptions will be removed in future issues.

We need a simple web page with a text field and a _run_ button. The text field specifies the path to the data directory. In the tutorial, this is `data/na_example`. Ultimately, in work beyond this issue the UI shouldn't use a text field, but rather a file explorer or functionality to upload files to the server. The text field just seems like the most trivial thing to do right now. If a file explorer is comparably trivial, that can be done first.

The training and validation label error rates should be output per epoch, along with notification when training is complete, reporting the test error rate.

**Comment by oadams** [comment]
Is there a case for using a web-based interface from the get-go?

**Comment by oadams** [comment]
It will be important to iron out the assumptions behind a standard workflow of a user working from ELAN files. For instance, determining how to address non-standard phoneme segmentation that can't be done with the greedy left-to-right segmenter of `preprocess.labels.segment_into_tokens`.

**Comment by oadams** [comment]
After some thought, it has become clear that the best way to go forward is for the UI to be a web interface to a (potentially local) server.

Pros:
- Persephone is not really meant to run on people's laptops. Setting it up so that users can harness GPUs on servers from the get-go is important because models will train faster and that faster turnaround time will affect people's perception of the tool. If it takes days to train a model on a laptop that a linguist cannot turn off, then that is a turn off.
- We sidestep issues of cross-platform support for Mac and Windows. Persephone just needs to run well on Linux and users can connect via a browser on any platform. If we go with tkinter.ttk we would have not been able to support Windows because that would potentially be too costly.
- If we went with tkinter.ttk the UI being developed would essentially be a throw-away temporary UI which would have to be replaced by a web interface in the future anyway. While the UI we do develop will be minimal, it can also be extensible and people can then adapt the interface to their use-case with more mainstream technologies such as JS, rather than having to write it from scratch.
- It takes a step towards institutional maintenance of a Persephone server. A number of non-technical linguists can benefit from one running server, with the effort of setting up the server (which will be straightforward for a computer scientist) being put on just one person with the right knowledge.

Cons:
- It makes the individual user's task of setting up Persephone slightly more difficult if there isn't already a running persephone server they can use. If previously one could just run the persephone application, they now need to either (a) have access to a server where Persephone is running, or (b) fire up persephone locally using the commandline and then connect via a a web interface.

I think the con listed above is a small price to pay for the benefits. With the right interface this con can be mitigated. In the TAP workshop a number of linguists managed to get docker containers fired up. If the drudgery of setting up the persephone server is captured in just the process of running a docker container with no further command line work, it's not such a big deal anyway.

**Comment by shuttle1987** [comment]
See work being done in https://github.com/aapeliv/persephone-frontend/ for a front end GUI.

**Comment by oadams** [comment]
Nice! Could you move that repo to the persephone-tools organization?

**Comment by shuttle1987** [comment]
Now that the repo is moved into the persephone-tools organization I'm going to close this
