### ISSUE TITLE
ReadyCorpus should auto-find untranscribed wavs

### ISSUE THREAD

**Issue by oadams** [persephone-tools/persephone#80]
WAV files in the data/wav/ directory supplied to ReadyCorpus should have their prefixes compared with transcriptions in data/label/. If no transcription is found, this should be noted in logs and they should be automatically added to the self.untranscribed_prefixes list.

**Comment by shuttle1987** [comment]
Status on this one? Want me to do this?

**Comment by oadams** [comment]
Sure, go for it!
